name: first

on: [push]

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step One One
              uses: actions/checkout@v4
            - name: Step One Two
              run: env | sort
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step Two One
              uses: actions/checkout@v4
            - name: Step Two Two
              run: "Get-Childitem Env: | Sort-Object Name"

    