name: Go Challenge Workflow

on: [push]

jobs:
    ubuntu:
        name: Ubuntu Job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Go Environment
              uses: actions/setup-go@v5
              with:
                go-version: "1.20"

            - name: Compile The Go File
              run: go build -o main main.go

            - name: Run The Compiled Binary
              run: ./main

    windows:
        name: Windows Job
        runs-on: windows-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Go Environment
              uses: actions/setup-go@v5
              with:
                go-version: "1.20"

            - name: Compile The Go File
              run: go build -o main.exe main.go

            - name: Run The Compiled Binary
              run: .\main.exe

    macos:
        name: macOS Job
        runs-on: macos-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Go Environment
              uses: actions/setup-go@v5
              with:
                go-version: "1.20"

            - name: Compile The Go File
              run: go build -o main main.go

            - name: Run The Compiled Binary
              run: ./main

    cross-compile:
        name: Cross Compile Jobs
        runs-on: ubuntu-latest
        needs: [ubuntu, windows, macos]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Go Environment
              uses: actions/setup-go@v5
              with:
                go-version: "1.20"

            - name: Compile for All Platforms
              run: |
                echo "Cross compiling for all platforms"
                GOOS=linux GOARCH=amd64 go build -o main-linux main.go
                GOOS=windows GOARCH=amd64 go build -o main-windows.exe main.go
                GOOS=darwin GOARCH=amd64 go build -o main-macos-intel main.go

            - name: List Binaries
              run: ls -1